[package]
name = "libadmin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
dotenv = "0.15.0"
jsonwebtoken = "8.2.0"
rocket = { version = "0.5.0-rc.2", features = ["json","serde_json",]}
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", branch = "master" }

[dependencies.rocket_db_pools]
version = "0.1.0-rc.2"
features = ["sqlx_postgres"]

[dependencies.sqlx]
default-features = false
features = ["macros", "migrate", "offline", "postgres"]



