
INSERT INTO books (book_name, book_author, book_publisher, book_price, book_description, category_id1, category_id2, category_id3)
VALUES 
  ('The Great Gatsby', 'F. Scott Fitzgerald', 'Scribner', 12.99, 'A classic novel about the Roaring Twenties.', 1, 3, 5),
  ('To Kill a Mockingbird', 'Harper Lee', 'J. B. Lippincott & Co.', 10.99, 'A Pulitzer Prize-winning novel about racial injustice.', 1, 4, 5),
  ('1984', 'George Orwell', 'Secker & Warburg', 9.99, 'A dystopian novel about totalitarianism.', 2, 3, 4),
  ('The Catcher in the Rye', 'J. D. Salinger', 'Little, Brown and Company', 11.99, 'A coming-of-age novel about a teenager in New York.', 1, 2, 5),
  ('Brave New World', 'Aldous Huxley', 'Chatto & Windus', 8.99, 'A dystopian novel about a future society.', 2, 3, 4),
  ('The Adventures of Huckleberry Finn', 'Mark Twain', 'Chatto & Windus', 13.99, 'A classic novel about a boy and a runaway slave.', 1, 4, 5),
  ('Pride and Prejudice', 'Jane Austen', 'T. Egerton', 14.99, 'A romantic novel about the Bennet sisters.', 1, 2, 3),
  ('The Hobbit', 'J. R. R. Tolkien', 'George Allen & Unwin', 15.99, 'A fantasy novel about hobbits, dwarves, and a dragon.', 2, 3, 5),
  ('Lord of the Flies', 'William Golding', 'Faber and Faber', 10.99, 'A novel about a group of boys stranded on an island.', 1, 2, 4),
  ('The Picture of Dorian Gray', 'Oscar Wilde', 'Ward, Lock, and Company', 7.99, 'A novel about a man who remains youthful while his portrait ages.', null, null, null),
  ('Crime and Punishment', 'Fyodor Dostoevsky', 'The Russian Messenger', 12.99, 'A psychological novel about a student who commits murder.', 1, 2, 4),
  ('The Scarlet Letter', 'Nathaniel Hawthorne', 'Ticknor, Reed & Fields', 9.99, 'A novel about a woman who has an affair and must wear a scarlet letter.', 1, 3, 5),
  ('Frankenstein', 'Mary Shelley', 'Lackington, Hughes, Harding, Mavor, & Jones', 11.99, 'A Gothic novel about a scientist who creates a monster.', 2, 3, 4),
  ('Heart of Darkness', 'Joseph Conrad', 'Blackwood''s Magazine', 8.99, 'A novella about a journey up the Congo River.', 1, 2, 5),
  ('Wuthering Heights', 'Emily Bronte', 'Thomas Cautley Newby', 10.99, 'A novel about the doomed love between Catherine and Heath cliff.', 1, 3, null),
('The Odyssey', 'Homer', 'N/A', 16.99, 'An epic poem about the Greek hero Odysseus and his journey home.', 2, 4, 5),
('The Iliad', 'Homer', 'N/A', 16.99, 'An epic poem about the Trojan War.', 2, 4, 5),
('The Divine Comedy', 'Dante Alighieri', 'N/A', 19.99, 'A long narrative poem about Dante''s journey through Hell, Purgatory, and Heaven.', 2, 3, 4),
('The Canterbury Tales', 'Geoffrey Chaucer', 'N/A', 14.99, 'A collection of stories told by pilgrims traveling to Canterbury.', 1, 2, 3),
('Don Quixote', 'Miguel de Cervantes', 'N/A', 13.99, 'A novel about a man who becomes a knight-errant and sets out to right the world''s wrongs.', 1, 3, 4),
('Moby-Dick', 'Herman Melville', 'N/A', 12.99, 'A novel about a captain''s obsession with hunting a giant white whale.', 1, 2, 5),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'N/A', 18.99, 'A novel about the relationships between three brothers and their father.', 1, 2, 4),
('Les Miserables', 'Victor Hugo', 'N/A', 17.99, 'A novel about the life of ex-convict Jean Valjean and his pursuit by Inspector Javert.', null, null, 5),
('War and Peace', 'Leo Tolstoy', 'N/A', 22.99, 'A novel about the French invasion of Russia and its effect on five Russian aristocratic families.', 1, 2, 4),
('The Stranger', 'Albert Camus', 'N/A', 8.99, 'A novel about a man who kills an Arab and must face the consequences.', 1, 3, 4),
('The Trial', 'Franz Kafka', 'N/A', 9.99, 'A novel about a man who is arrested and prosecuted by a mysterious, impersonal authority.', 1, 2, 4),
('The Metamorphosis', 'Franz Kafka', 'N/A', 6.99, 'A novella about a man who wakes up one day to find he has turned into a giant insect.', 1, 3, 4),
('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 'N/A', 15.99, 'A novel about the Buendia family in the town of Macondo.', 1, 2, 5),
('The Old Man and the Sea', 'Ernest Hemingway', 'N/A', 7.99, 'A novella about an aging fisherman and his battle with a giant marlin.', 1, 3, 4),
('The Sun Also Rises', 'Ernest Hemingway', 'N/A', 10.99, 'A novel about a group of American and British expatriates in Paris.', 1, 2, 5),
('The Sound and the Fury', 'William Faulkner', 'N/A', 11.99 , 'A novel about the decline of the Compson family in the American South.', 1, 2, 4),
('To Kill a Mockingbird', 'Harper Lee', 'N/A', 14.99, 'A novel about racism and injustice in a small Southern town during the 1930s.', 1, 3, 5),
('The Catcher in the Rye', 'J.D. Salinger', 'N/A', 9.99, 'A novel about teenage angst and alienation in post-World War II America.', 1, 3, 4),
('The Great Gatsby', 'F. Scott Fitzgerald', 'N/A', 12.99, 'A novel about the life of Jay Gatsby and his pursuit of the American Dream.', 1, 2, 5),
('1984', 'George Orwell', 'N/A', 8.99, 'A dystopian novel about a totalitarian society in which citizens are controlled by the government.', 1, 2, 4),
('Animal Farm', 'George Orwell', 'N/A', 7.99, 'A novella about a group of farm animals who overthrow their human owner and try to create a utopian society.', 1, 3, 4),
('Pride and Prejudice', 'Jane Austen', 'N/A', 10.99, 'A novel about the romantic relationships of the Bennet sisters and their eventual marriages.', 1, 2, 3),
('Sense and Sensibility', 'Jane Austen', 'N/A', 9.99, 'A novel about two sisters and their pursuit of happiness and love.', 1, 3, 4),
('Wuthering Heights', 'Emily Bronte', 'N/A', 11.99, 'A novel about the doomed love affair between Catherine Earnshaw and Heathcliff.', 1, 2, 5),
('Jane Eyre', 'Charlotte Bronte', 'N/A', 12.99, 'A novel about the life of Jane Eyre and her relationship with the brooding Mr. Rochester.', null, 2, 4),
('The Picture of Dorian Gray', 'Oscar Wilde', 'N/A', 8.99, 'A novel about a man who sells his soul to the devil in exchange for eternal youth and beauty.', 1, 3, 4),
('Dracula', 'Bram Stoker', 'N/A', 10.99, 'A novel about Count Dracula''s attempt to move from Transylvania to England so he may find new blood and spread the undead curse.', 1, 2, 5),
('Frankenstein', 'Mary Shelley', 'N/A', 9.99, 'A novel about a scientist who creates a monster and the consequences that follow.', 1, 3, 4),
('The Adventures of Huckleberry Finn', 'Mark Twain', 'N/A', 11.99, 'A novel about the adventures of a boy and a runaway slave on the Mississippi River.', 1, 2, 4),
('The Adventures of Tom Sawyer', 'Mark Twain', 'N/A', 9.99, 'A novel about a young boy growing up in a small town on the Mississippi River.', 1, 3, 5);
